### ISSUE TITLE
collectionView:didSelectItemAt not being called

### ISSUE THREAD

**Issue by AphroditeSoftware** [LeeKahSeng/SwiftSenpai-UICollectionView-List#7]
I'm attempting to use the samples for Custom Cell and respond to collectionView:didSelectItemAt. I've added the following to CustomCellListViewController, after setting the class to be the collectionView delegate during viewDidLoad. 

```
extension CustomCellListViewController: UICollectionViewDelegate {
    
    func collectionView(_collectionView: UICollectionView, didSelectItemAt indexPath: IndexPath) {
        print("tapped")
    }
}

```

The function is not called. I've also tried in the NameListViewController and same result. 

How does one add handling a cell selection with the custom ContentView classes involved?

**Comment by LeeKahSeng** [comment]
The delegate method you are using is not correct, there should be a space between `_` and `collectionView:`. Please use the following instead.

```swift
extension CustomCellListViewController: UICollectionViewDelegate {
    
    func collectionView(_ collectionView: UICollectionView, didSelectItemAt indexPath: IndexPath) {
        print("tapped")
    }
}
```

**Comment by AphroditeSoftware** [comment]
Well that was simple and thank you.
